server:
  port: 8080
  error:
    include-message: always
    include-exception: false
spring:
  h2:
    console:
      enabled: true
      setting:
        web-admin-password: example
        web-allow-others: true


database:
  url: jdbc:h2:file:./database/db_cards
  username: sa
  password: example